Make redacted_claim_keys use a tagged CWT key
ietf-wg-spice/draft-ietf-spice-sd-cwt pull request #31
Opened 2024-11-19 14:39 UTC by rohanmahy

- Replace `/redacted_claim_keys/ -65536: [ <digest1>, <digest2> ]` with `59(0): [ <digest1>, <digest2> ]`

2024-11-19 14:57 UTC, OR13 approved these changes

2024-11-20 14:06 UTC, mprorock approved these changes

2024-11-20 14:21 UTC, OR13 requested changes
holding this PR until we hear back from the list

2024-11-27 13:31 UTC, OR13 commented
There is a proposal to use simple values instead of tags: https://mailarchive.ietf.org/arch/msg/spice/1qHebZZ1rxS7QvDao9ENYswbiU0/

unfortunately it appears that simple values are not well supported in CBOR tooling, for at least the rust language.

I suggest we proceed with the tag approach and upgrade to simple values if the tooling situation improves.

2024-11-27 13:32 UTC, OR13 approved these changes

2024-11-27 14:08 UTC, rohanmahy commented
Merging. If we see strong library support for a new simple type, we can introduce a very short PR to change it.

2024-11-27 14:08 UTC, merged